document.getElementById('container').style.background="Black"
document.querySelector('#header-container').style.background="Green"
document.querySelectorAll('.emergency-tasks')[0].style.background="Red"
document.getElementsByTagName('section')[1].style.background="blue"
document.getElementById('footer-container').style.background="brown"
document.getElementsByTagName('h3')[1].style.color="purple"